services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=shield_pay'
      - 'POSTGRES_PASSWORD=teste123'
      - 'POSTGRES_USER=developer'
    ports:
      - '5432'
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672'
